### ISSUE TITLE
Provide .alfredworkflow file

### ISSUE THREAD

**Issue by hootlex** [radibit/alfred-keycode#1]
Unfortunately npm script fails. Could you provide a `.alfredworkflow` file for convenience? Thanks :)

**Comment by radibit** [comment]
Hey @hootlex, could you please provide me with more information about your npm scripts failure e.g. `node version`, `npm version`, and OS? I've just re-installed it successfully on 

```
macOS Sierra 10.12.5
node v6.7.0
npm 4.6.1
```

On your exact question, I can upload the `.alfredworkflow` on http://www.packal.org/, but I'm traveling at the moment and I can do that in the next days.

**Comment by hootlex** [comment]
Hi @radibit and thanks for the quick response.
Here are my system info:
```
macOS Sierra 10.12.5
node v7.4.0
npm 4.6.1
```

I am also attaching the error:

![error](http://i.imgur.com/Colyyo7.png)

**Comment by radibit** [comment]
Hi @hootlex Thank you for the provided info and especially for the screenshot. I noticed that you were using `postinstall` command. However, this npm script together with `preuninstall` are needed when you want to publish an Alfred workflow as npm package (in this case `alfred-keycode` has been already published). For more info on that you can check [Alfy documentation](https://github.com/sindresorhus/alfy#publish-to-npm). 

In order to install this workflow you can use `npm i -g alfred-keycode` and it will be imported automatically to your Alfred workflows. As another option (and as per your request) you can download directly the workflow from Packal on the following link [alfred-keycode](http://www.packal.org/workflow/alfred-keycode). 

Please let me know if you have any other questions, otherwise I will consider this issue as closed.

**Comment by hootlex** [comment]
Hey @radibit, thanks a lot for you help.
I was already using `npm i -g alfred-keycode` to install the workflow. This is where I got the above error.

I'll go with the `.alfreadworkflow`. Let me know if you need help debugging the script. 🙂

**Comment by hootlex** [comment]
The download link on packal.org is broken.

**Comment by radibit** [comment]
Hey @hootlex 

> I was already using npm i -g alfred-keycode to install the workflow. This is where I got the above error.

I need to have a closer look on this as it's not possible for me to reproduce this error at the moment.

> The download link on packal.org is broken.

Looks like the download link is still not updated on packal's repository. I already pushed it here to this repository and you can download it from the following [link](https://github.com/radibit/alfred-keycode/raw/master/keycode.alfredworkflow)

Sorry for the troubles and I hope it will now work for you 🙂

**Comment by hootlex** [comment]
Awesome, thank you!
